language: objective-c
env:
  - RVM_RUBY_VERSION=system
  - RVM_RUBY_VERSION=1.9.3 LANG=en_US.UTF-8 LC_CTYPE=UTF-8
before_install: source ~/.rvm/scripts/rvm && rvm use $RVM_RUBY_VERSION
install: bundle install
script: bundle exec rake
